CREATE TABLE "MGMT_ITEM" (
    "ITEM_ID" bigint NOT NULL,
    "ITEM_NAME" character varying NOT NULL,
    "ITEM_CATE_ID" integer NOT NULL,
    "ITEM_TRAIT_ID" integer NOT NULL,
    "ITEM_ORDER" integer NOT NULL
);

CREATE TABLE "MGMT_ITEM_CATEGORY" (
    "ITEM_CATE_ID" integer NOT NULL,
    "ITEM_CATE_NAME" character varying NOT NULL,
    "ITEM_CATE_ORDER" smallint NOT NULL
);


CREATE TABLE "MGMT_ITEM_TRAIT" (
    "ITEM_TRAIT_ID" integer NOT NULL,
    "ITEM_TRAIT_NAME" character varying NOT NULL
);

CREATE TABLE "MGMT_ITEM_TRAIT_DTL" (
    "ITEM_TRAIT_DTL_ID" integer NOT NULL,
    "ITEM_TRAIT_DTL_NAME" character varying NOT NULL,
    "ITEM_TRAIT_ID" integer NOT NULL,
    "ITEM_TRAIT_DTL_ORDER" smallint NOT NULL
);

CREATE TABLE "MGMT_ITEM_TRAIT_SETTING" (
    "ITEM_TRAIT_SETTING_ID" bigint NOT NULL,
    "ITEM_ID" integer NOT NULL,
    "ITEM_TRAIT_DTL_ID" integer NOT NULL,
    "ITEM_TRAIT_SETTING_VALUE" character varying NOT NULL,
    "ITEM_TRAIT_SETTING_ORDER" smallint NOT NULL
);

CREATE TABLE "MGMT_ORG_ENTITY" (
    "ENTITY_ID" bigint NOT NULL,
    "ENTITY_HICHY_ID" integer NOT NULL,
    "ENTITY_DESC" character varying NOT NULL,
    "UPPER_ENTITY_ID" bigint
);

CREATE TABLE "MGMT_ORG_HICHY" (
    "DEPT_HICHY_ID" integer NOT NULL,
    "DEPT_HICHY_NAME" character varying NOT NULL
);


ALTER TABLE ONLY "MGMT_ITEM_CATEGORY"
    ADD CONSTRAINT "MGMT_ITEM_CATEGORY_pkey" PRIMARY KEY ("ITEM_CATE_ID");

ALTER TABLE ONLY "MGMT_ITEM_TRAIT_DTL"
    ADD CONSTRAINT "MGMT_ITEM_TRAIT_DTL_pkey" PRIMARY KEY ("ITEM_TRAIT_DTL_ID");

ALTER TABLE ONLY "MGMT_ITEM_TRAIT_SETTING"
    ADD CONSTRAINT "MGMT_ITEM_TRAIT_SETTING_pkey" PRIMARY KEY ("ITEM_TRAIT_SETTING_VALUE");

ALTER TABLE ONLY "MGMT_ITEM_TRAIT"
    ADD CONSTRAINT "MGMT_ITEM_TRAIT_pkey" PRIMARY KEY ("ITEM_TRAIT_ID");

ALTER TABLE ONLY "MGMT_ORG_ENTITY"
    ADD CONSTRAINT "MGMT_ORG_DEPT_pkey" PRIMARY KEY ("ENTITY_ID");

ALTER TABLE ONLY "MGMT_ORG_HICHY"
    ADD CONSTRAINT "MGMT_ORG_HICHY_pkey" PRIMARY KEY ("DEPT_HICHY_ID");

ALTER TABLE ONLY "MGMT_ITEM"
    ADD CONSTRAINT "MGMT_ORG_REPO_pkey" PRIMARY KEY ("ITEM_ID");

ALTER TABLE ONLY "MGMT_ORG_ENTITY"
    ADD CONSTRAINT "FK_ENTITY_HICHY_ID" FOREIGN KEY ("ENTITY_HICHY_ID") REFERENCES "MGMT_ORG_HICHY"("DEPT_HICHY_ID");

ALTER TABLE ONLY "MGMT_ITEM"
    ADD CONSTRAINT "FK_ITEM_CATE_ID" FOREIGN KEY ("ITEM_CATE_ID") REFERENCES "MGMT_ITEM_CATEGORY"("ITEM_CATE_ID");

ALTER TABLE ONLY "MGMT_ITEM_TRAIT_SETTING"
    ADD CONSTRAINT "FK_ITEM_ID" FOREIGN KEY ("ITEM_ID") REFERENCES "MGMT_ITEM"("ITEM_ID");

ALTER TABLE ONLY "MGMT_ITEM_TRAIT_SETTING"
    ADD CONSTRAINT "FK_ITEM_TRAIT_DTL_ID" FOREIGN KEY ("ITEM_TRAIT_DTL_ID") REFERENCES "MGMT_ITEM_TRAIT_DTL"("ITEM_TRAIT_DTL_ID");

ALTER TABLE ONLY "MGMT_ITEM_TRAIT_DTL"
    ADD CONSTRAINT "FK_ITEM_TRAIT_ID" FOREIGN KEY ("ITEM_TRAIT_ID") REFERENCES "MGMT_ITEM_TRAIT"("ITEM_TRAIT_ID");

ALTER TABLE ONLY "MGMT_ITEM"
    ADD CONSTRAINT "FK_ITEM_TRAIT_ID" FOREIGN KEY ("ITEM_TRAIT_ID") REFERENCES "MGMT_ITEM_TRAIT"("ITEM_TRAIT_ID");

ALTER TABLE ONLY "MGMT_ORG_ENTITY"
    ADD CONSTRAINT "FK_UPPER_ENTITY_ID" FOREIGN KEY ("UPPER_ENTITY_ID") REFERENCES "MGMT_ORG_ENTITY"("ENTITY_ID");

